image: gitpod/workspace-python-3.11@sha256:88e108b93dde90bf4fbe14292549ac63f058c67cf89b835c56f180b4aed54a54

tasks:
  - init: poetry install # pip install -r requirements.txt
    command: poetry run python3 -m python

vscode:
  extensions:
    - ms-python.python
    - ms-python.isort
